[pytest]
addopts = --cov-config=.coveragerc --cov --cov-report html --cov-report term --cov-report xml --junitxml=test-results.xml -vv -n auto --dist loadfile
pythonpath = .
markers =
    serial: mark test to run serially (in single xdist group)
