#!/usr/bin/python
from __future__ import print_function
import sys
from sonic_py_common import multi_asic
from swsscommon.swsscommon import SonicDBConfig, SonicDBKey
import redis
import argparse
import os
import time


SCAN_BATCH_SIZE = 7000


def copy_database(source, target):
    cursor = 0
    while True:
        cursor, keys = source.scan(cursor=cursor, count=SCAN_BATCH_SIZE)
        if keys:
            # Read each value and its expiry in one Redis transaction so they
            # describe the same version of the key.
            source_pipeline = source.pipeline()
            for key in keys:
                source_pipeline.dump(key)
                source_pipeline.pttl(key)
            read_started = int(time.time() * 1000)
            values = source_pipeline.execute()
            read_elapsed = int(time.time() * 1000) - read_started

            target_pipeline = target.pipeline()
            restore_count = 0
            for index, key in enumerate(keys):
                value = values[index * 2]
                ttl = values[index * 2 + 1]
                if value is None or ttl == -2:
                    continue
                if ttl < 0:
                    ttl = 0
                else:
                    ttl = max(ttl - read_elapsed, 1)
                target_pipeline.execute_command('RESTORE', key, ttl, value, 'REPLACE')
                restore_count += 1

            if restore_count:
                target_pipeline.execute()

        if cursor == 0:
            break


def centralize_to_target_db(target_dbname, namespace):
    if multi_asic.is_multi_asic():
        SonicDBConfig.initializeGlobalConfig()
    key = SonicDBKey(namespace)
    target_dbsocket = SonicDBConfig.getDbSock(target_dbname, key)
    if not target_dbsocket:
        raise RuntimeError("No Unix socket configured for {}".format(target_dbname))

    dblists = SonicDBConfig.getDbList(key)
    for dbname in dblists:
        dbsocket = SonicDBConfig.getDbSock(dbname, key)
        if not dbsocket:
            raise RuntimeError("No Unix socket configured for {}".format(dbname))
        # If the DB is already on the target instance, no copy is needed.
        if dbsocket == target_dbsocket:
            continue

        dbid = SonicDBConfig.getDbId(dbname, key)

        source = redis.Redis(unix_socket_path=dbsocket, db=dbid)
        target = redis.Redis(unix_socket_path=target_dbsocket, db=dbid)
        copy_database(source, target)

    #SAVE rdb file
    target = redis.Redis(unix_socket_path=target_dbsocket)
    target.save()

def main():
    parser = argparse.ArgumentParser(description='centralize all db data into one db instances',
                                     formatter_class=argparse.RawTextHelpFormatter,
                                     epilog=
"""
Example : centralize_database APPL_DB
""")
    parser.add_argument('target_db', type=str, help='move all db data into the instance where target db locates')
    parser.add_argument('-n', '--namespace', default=multi_asic.DEFAULT_NAMESPACE, type=str, help='namespace to use')
    args = parser.parse_args()

    if args.target_db:
        try:
            centralize_to_target_db(args.target_db, args.namespace)
            print(SonicDBConfig.getDbInst(args.target_db, SonicDBKey(args.namespace)))
        except Exception as ex:
            template = "An exception of type {0} occurred. Arguments:\n{1!r}"
            message = template.format(type(ex).__name__, ex.args)
            print(message, file=sys.stderr)
            sys.exit(1)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
